### PR TITLE
fix: make apply now links open in new tab

### PR DESCRIPTION
**Pull request by meghrathod**
This is helpful when trying to fill multiple applications, keeping the github page open rather than having to open it again for the next application. I have also updated it in the issue scripts. Do verify and let me know.

### CODE REVIEW

**Comment by vanshb03** [comment]
Hey @meghrathod,

Thank you for your contribution, just tried it out and the links aren't opening on another tab from the looks of it.

Happy to take a look at it later today on what could be causing that.

**Comment by vanshb03** [comment]
For the time being; feel free to use CTRL+click (on Windows and Linux) or CMD+click (on MacOS) on the link, the get the same behavior

**Comment by meghrathod** [comment]
https://stackoverflow.com/questions/41915571/open-link-in-new-tab-with-github-markdown-using-target-blank

Okay it seems, this doesn't work on Chrome. I used Arc browser on Mac and for some reason, it supports this. Anyways, if you want to close the pull request or merge it is on you. If you were incase thinking of creating a GitHub pages for the Readme, then open in new tab will work.

**Comment by akhilreddy-danda** [comment]
This will be so helpful.

**Pull request closed without merging**
